# not the standard ROS node config parameters, these are topics passed to the vision pipeline launch file
camera:
  front_cam_topic: /zed/zed_node/rgb/color/rect/image/compressed # TODO: SIMPLIFY THE CONFIGS TO NOT GET LOST 
  down_cam_topic: /vision/down_cam/image_raw

image_enhancement:
  front_enhanced_topic: /vision/front_cam/image_enhanced
  down_enhanced_topic: /vision/down_cam/image_enhanced
  log_level: info

object_detection:
  front_detections_topic: /vision/front_cam/detections
  down_detections_topic: /vision/down_cam/detections
# relative to src directory
  front_model_relative_path: models/frontcam.engine
  down_model_relative_path: models/downcam.pt
  log_level: info

object_map:
  map_topic: /vision/object_map
  pose_topic: /vision/vio_pose
  confidence_threshold: 0.5
  zed_depth_confidence_threshold: 90
  max_range: 10.0
  use_stream: true
  stream_ip: "127.0.0.1"
  stream_port: 30000
  frame_rate: 30
  show_detections: false
  new_object_min_distance_threshold: 0.5
  pool_floor_z: -2.1
  pool_surface_z: 0.0
  gating_threshold: 3.5
  min_hits: 20
  max_age: 8
  max_position_jump: 2.0
  conf_to_tent_threshold: 5
  tent_init_buffer: 5
  log_level: info

general:
  sim: false
