name: Cleanup disk
description: Github actions contains many packages we don't need for our docker builds (e.g. .NET, Android SDK, GHC, hosted toolcache). This action removes them to free up disk space.

runs:
  using: composite
  steps:
    - shell: bash
      name: Cleanup
      run: |
        echo "=== Before Cleanup ==="
        df -h

        # 1. Android Library
        sudo rm -rf /usr/local/lib/android

        # 2. .NET Runtime
        sudo rm -rf /usr/share/dotnet

        # 3. Haskell / GHC
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup

        # 4. CodeQL Analysis
        sudo rm -rf /opt/hostedtoolcache/CodeQL

        # 5. Swift & Java
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/lib/jvm

        # 6. Docker Cache (Pre-loaded images)
        sudo docker image prune -af
        sudo docker builder prune -af

        echo "=== After Cleanup ==="
        df -h