save_dir: "~/AUV-2026/rosbags"

# Rosbag profiles define lists of topics to record or exclude.
# Each profile can specify 'topics' (to record) and/or 'exclude' (topics to ignore).
# Use regex (e.g., '.*') for patterns.

profiles:
  all:
    topics:
      - ".*"
    exclude:
      - ".*/annotated/compressed$" # Excludes the 30Hz annotated images, keeping the 5Hz _throttled versions
      # - ".*/depth/compressed$" # Depth is already happening at 5Hz, so it's fine

  all_no_vision:
    topics:
      - ".*"
    exclude:
      - ".*image.*"
      - ".*pointcloud.*"
      - "/vision/.*"
      - "/zed/.*"

  vision:
    topics:
      - "/zed/.*"
      - "/vision/.*"
    exclude:
      - ".*/annotated/compressed$" # Excludes the raw 30Hz annotated images, but captures the 5Hz _throttled ones
      - ".*/depth/compressed$" # Excludes the raw 30Hz depth images, but captures the 5Hz _throttled ones
      
  nav_and_controls:
    topics:
      - "/planner_root_tree/.*"
      - "/imu/.*"
      - "/filter/.*"
      - "/gnss.*"
      - "/odometry"
      - "/pressure"
      - "/temperature"
      - "/rtcm"
      - "/nmea"
      - "/dvl/.*"
      - "/auv_frame/.*"
      - "/auv_state/.*"
      - "/controls/.*"
      - "/propulsion/.*"
