front_rgb_throttler:
  ros__parameters:
    throttle_type: "messages"
    msgs_per_sec: 5.0
    input_topic: "/vision/front_cam/detection_frame/annotated/compressed"
    output_topic: "/vision/front_cam/detection_frame/annotated/compressed_throttled"

down_rgb_throttler:
  ros__parameters:
    throttle_type: "messages"
    msgs_per_sec: 5.0
    input_topic: "/vision/down_cam/detections/annotated/compressed"
    output_topic: "/vision/down_cam/detections/annotated/compressed_throttled"

front_depth_throttler:
  ros__parameters:
    throttle_type: "messages"
    msgs_per_sec: 5.0
    input_topic: "/vision/front_cam/detection_frame/depth"
    output_topic: "/vision/front_cam/detection_frame/depth_throttled"
