thrust_mapper: 

  # Maximum thrust values that can be commanded for each thruster (in Newtons)
  max_thrust_t1: 40.0
  max_thrust_t2: 40.0
  max_thrust_t3: 40.0
  max_thrust_t4: 40.0
  max_thrust_t5: 40.0
  max_thrust_t6: 40.0
  max_thrust_t7: 40.0
  max_thrust_t8: 40.0

  # Minimum thrust values that can be commanded for each thruster (in Newtons)
  min_thrust_t1: -20.0
  min_thrust_t2: -20.0
  min_thrust_t3: -20.0
  min_thrust_t4: -20.0
  min_thrust_t5: -20.0
  min_thrust_t6: -20.0
  min_thrust_t7: -20.0
  min_thrust_t8: -20.0
