attitude_controller:
    ros__parameters:
        control_loop_rate: 25.0
        # P
        P_ex: 5.73 # v2 -> 0.01 10.9388
        P_ey: 7.46 # v2 -> 0.01 10.9388
        P_ez: 7.53 # v2 -> 3.5
        # I
        I_ex: 0.2176 # 0.5008
        I_ey: 0.3221 # 0.5008
        I_ez: 0.4565 # may need to modify (0.5 in v2)
        # D
        P_wx: 2.37 # v2 -> 0.1 3.1112
        P_wy: 2.92 # v2 -> 0.1 3.1112
        P_wz: 3.46 # v2 -> 2.0
        I_MAX: 3.0
        integral_activation_threshold_deg: 100000.0
        max_slew_rate_roll_deg: 0.0 # [deg/s] (0.0 = disabled)
        max_slew_rate_pitch_deg: 0.0 # [deg/s]
        max_slew_rate_yaw_deg: 0.0 # [deg/s]
        buoyancy: 275.4 # [N]
        r_bv_v: [ 0.0, 0.0, 0.0 ] # [m] Tuned in pool tests.    
        enabled: true

# P_ex=5.73, I_ex=0.2176, P_wx=2.37, P_ey=7.46, I_ey=0.3221, P_wy=2.92, P_ez=7.53, I_ez=0.4565, P_wz=3.46

depth_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 58.92
        KD: 71.12
        KI: 9.2821 # may need to modify
        I_MAX: 10.0
        integral_activation_threshold: 0.3
        derivative_filter_alpha: 0.2
        max_slew_rate: 0.0 # [m/s] (0.0 = disabled)
        net_buoyancy: 3.5 # Newtons.
        enabled: true

x_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 50.82
        KD: 50.12
        KI: 0.9728
        I_MAX: 10.0
        integral_activation_threshold: 0.5
        derivative_filter_alpha: 0.8
        max_slew_rate: 0.0 # [m/s] (0.0 = disabled)
        enabled: true

y_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 51.82
        KD: 47.87
        KI: 2.7884
        I_MAX: 10.0
        integral_activation_threshold: 0.5
        derivative_filter_alpha: 0.8
        max_slew_rate: 0.0 # [m/s] (0.0 = disabled)
        enabled: true

superimposer:
    ros__parameters:
        effort_bias_force_x: 0.0
        effort_bias_force_y: 0.0
        effort_bias_force_z: 0.0
        effort_bias_torque_x: 0.0
        effort_bias_torque_y: 0.0
        effort_bias_torque_z: 0.0
        publish_hz: 40.0
        # Safety Effort Limits (0.0 = disabled)
        max_planar_effort: 30.0      # Max magnitude of sqrt(Fx^2 + Fy^2) [N]
        max_depth_effort: 40.0       # Max absolute vertical force [N]
        max_torque_x: 10.0           # Max absolute roll torque [Nm]
        max_torque_y: 10.0           # Max absolute pitch torque [Nm]
        max_torque_z: 10.0           # Max absolute yaw torque [Nm]
        enabled: true
