attitude_controller:
    ros__parameters:
        control_loop_rate: 25.0
        # P
        P_ex: 0.05 # v2 -> 0.01
        P_ey: 0.05 # v2 -> 0.01
        P_ez: 6.0 # v2 -> 3.5
        # I
        I_ex: 0.0
        I_ey: 0.0
        I_ez: 0.0 # may need to modify (0.5 in v2)
        # D
        P_wx: 0.1 # v2 -> 0.1
        P_wy: 0.1 # v2 -> 0.1
        P_wz: 2.0 # v2 -> 2.0
        I_MAX: 3.0
        integral_activation_threshold_deg: 10.0
        buoyancy: 275.4 # [N]
        r_bv_v: [ 0.0, 0.0, 0.0 ] # [m] Tuned in pool tests.    
        enabled: true

depth_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 30.0
        KD: 50.0
        KI: 0.15 # may need to modify
        I_MAX: 10.0
        integral_activation_threshold: 0.3
        net_buoyancy: 3.5 # Newtons.
        enabled: true

x_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 10.0
        KD: 6.0
        KI: 0.5
        I_MAX: 10.0
        integral_activation_threshold: 0.5
        enabled: true

y_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 10.0
        KD: 6.0
        KI: 0.5
        I_MAX: 10.0
        integral_activation_threshold: 0.5
        enabled: true
