attitude_controller:
  ros__parameters:
    control_loop_hz: 10.0
    P_ex_large: 6.0
    P_ey_large: 6.0
    P_ez_large: 6.0
    P_wx_large: 1.0
    P_wy_large: 1.0
    P_wz_large: 1.0

    P_ex_sas: 6.0
    P_ey_sas: 6.0
    P_ez_sas: 6.0
    P_wx_sas: 1.0
    P_wy_sas: 1.0
    P_wz_sas: 1.0

    I_ex_large: 0.0
    I_ey_large: 0.0
    I_ez_large: 0.5
    I_ex_sas: 0.0
    I_ey_sas: 0.0
    I_ez_sas: 0.5
    I_max: 3.0
    integral_activation_deg: 25.0

    sas_switch_deg: 5.0
    buoyancy: 264.09 # [N]
    r_bv_v: [0.0, 0.0, 0.023] # [m] From CAD Model    
    enabled: true

depth_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 10.0
        KD: 50.0
        KI: 0.0
        I_MAX: 10.0
        integral_activation_threshold: 0.5
        net_buoyancy: 9.03 # Newtons
        enabled: true

x_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 15.0
        KD: 50.0
        KI: 0.5
        I_MAX: 10.0
        integral_activation_threshold: 1.0
        enabled: true

y_controller:
    ros__parameters:
        control_loop_hz: 10.0
        KP: 15.0
        KD: 50.0
        KI: 0.5
        I_MAX: 10.0
        integral_activation_threshold: 1.0
        enabled: true

superimposer:
    ros__parameters:
        effort_bias_force_x: 0.0
        effort_bias_force_y: 0.0
        effort_bias_force_z: 0.0
        effort_bias_torque_x: 0.0
        effort_bias_torque_y: 0.0
        effort_bias_torque_z: 0.0
        publish_hz: 50.0
        max_planar_effort: 0.0
        max_depth_effort: 0.0
        max_attitude_effort: 0.0
